# Generated by Django 4.0.4 on 2022-05-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10)),
                ('habilitada', models.BooleanField()),
            ],
            options={
                'db_table': 'pro_categoria_producto',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'pro_marca',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca_id', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=10)),
                ('caracteristica', models.BooleanField()),
                ('color', models.CharField(max_length=10)),
                ('utilidad', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=10)),
                ('garantia', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=10)),
                ('url_imagen_producto', models.ImageField(null=True, upload_to='imagenes')),
            ],
            options={
                'db_table': 'pro_producto',
            },
        ),
    ]
