# Generated by Django 4.0.4 on 2022-05-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='url_imagen_producto',
            field=models.ImageField(upload_to='Uploaded Files/'),
        ),
    ]
